/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as TurnoTokenRouteImport } from './routes/turno.$token'
import { Route as ApiPublicCronExpirePendingRouteImport } from './routes/api/public/cron/expire-pending'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnoTokenRoute = TurnoTokenRouteImport.update({
  id: '/turno/$token',
  path: '/turno/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronExpirePendingRoute =
  ApiPublicCronExpirePendingRouteImport.update({
    id: '/api/public/cron/expire-pending',
    path: '/api/public/cron/expire-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/api/public/cron/expire-pending': typeof ApiPublicCronExpirePendingRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/api/public/cron/expire-pending': typeof ApiPublicCronExpirePendingRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/reservar': typeof ReservarRoute
  '/turno/$token': typeof TurnoTokenRoute
  '/api/public/cron/expire-pending': typeof ApiPublicCronExpirePendingRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reservar'
    | '/turno/$token'
    | '/api/public/cron/expire-pending'
    | '/api/public/cron/reminders'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/reservar'
    | '/turno/$token'
    | '/api/public/cron/expire-pending'
    | '/api/public/cron/reminders'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/reservar'
    | '/turno/$token'
    | '/api/public/cron/expire-pending'
    | '/api/public/cron/reminders'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRoute
  ReservarRoute: typeof ReservarRoute
  TurnoTokenRoute: typeof TurnoTokenRoute
  ApiPublicCronExpirePendingRoute: typeof ApiPublicCronExpirePendingRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turno/$token': {
      id: '/turno/$token'
      path: '/turno/$token'
      fullPath: '/turno/$token'
      preLoaderRoute: typeof TurnoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/expire-pending': {
      id: '/api/public/cron/expire-pending'
      path: '/api/public/cron/expire-pending'
      fullPath: '/api/public/cron/expire-pending'
      preLoaderRoute: typeof ApiPublicCronExpirePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRoute,
  ReservarRoute: ReservarRoute,
  TurnoTokenRoute: TurnoTokenRoute,
  ApiPublicCronExpirePendingRoute: ApiPublicCronExpirePendingRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
